server:
  port: 8084

spring:
  application:
    name: agent-service
  datasource:
    url: jdbc:mariadb://mariadb:3306/agentflow
    username: agentflow
    password: agentflow
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: agent-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "viettel.dac.agentservice.dto"
  elasticsearch:
    rest:
      uris: http://elasticsearch:9200

conversation:
  max-history-size: 20
  inactivity-timeout: 1800000  # 30 minutes in milliseconds

logging:
  level:
    viettel.dac.agentservice: DEBUG