server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: identity-service
          uri: lb://identity-service
          predicates:
            - Path=/api/auth/**, /api/users/**, /api/organizations/**, /api/projects/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
        - id: prompt-service
          uri: lb://prompt-service
          predicates:
            - Path=/api/prompts/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
        - id: flow-service
          uri: lb://flow-service
          predicates:
            - Path=/api/flows/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
        - id: agent-service
          uri: lb://agent-service
          predicates:
            - Path=/api/agents/**, /api/conversations/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
        - id: integration-service
          uri: lb://integration-service
          predicates:
            - Path=/api/integrations/**, /api/webhooks/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://identity-service:8081
          jwk-set-uri: http://identity-service:8081/.well-known/jwks.json

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework.cloud.gateway: INFO
    reactor.netty: INFO