server:
  port: 8761

spring:
  application:
    name: service-registry

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false
    wait-time-in-ms-when-sync-empty: 0
    response-cache-update-interval-ms: 5000
  instance:
    hostname: service-registry
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"