version: '3.8'

services:
  # First Eureka Server Instance
  eureka-1:
    build:
      context: .
      dockerfile: Dockerfile
    image: agentflow/service-registry:latest
    container_name: eureka-1
    hostname: eureka-1
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=peer
      - EUREKA_INSTANCE_HOSTNAME=eureka-1
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://admin:admin@eureka-2:8761/eureka/
      - SPRING_SECURITY_USER_NAME=admin
      - SPRING_SECURITY_USER_PASSWORD=admin
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - eureka-net

  # Second Eureka Server Instance
  eureka-2:
    build:
      context: .
      dockerfile: Dockerfile
    image: agentflow/service-registry:latest
    container_name: eureka-2
    hostname: eureka-2
    ports:
      - "8762:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=peer
      - EUREKA_INSTANCE_HOSTNAME=eureka-2
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://admin:admin@eureka-1:8761/eureka/
      - SPRING_SECURITY_USER_NAME=admin
      - SPRING_SECURITY_USER_PASSWORD=admin
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - eureka-net

  # Optional third Eureka Server Instance for larger deployments
  eureka-3:
    build:
      context: .
      dockerfile: Dockerfile
    image: agentflow/service-registry:latest
    container_name: eureka-3
    hostname: eureka-3
    ports:
      - "8763:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=peer
      - EUREKA_INSTANCE_HOSTNAME=eureka-3
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://admin:admin@eureka-1:8761/eureka/,http://admin:admin@eureka-2:8761/eureka/
      - SPRING_SECURITY_USER_NAME=admin
      - SPRING_SECURITY_USER_PASSWORD=admin
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - eureka-net

  # Test client for verification (optional)
  test-client:
    image: agentflow/test-client:latest
    container_name: test-client
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://admin:admin@eureka-1:8761/eureka/,http://admin:admin@eureka-2:8761/eureka/,http://admin:admin@eureka-3:8761/eureka/
    depends_on:
      eureka-1:
        condition: service_healthy
      eureka-2:
        condition: service_healthy
    networks:
      - eureka-net

networks:
  eureka-net:
    driver: bridge