global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'identity-service'
    metrics_path: '/api/actuator/prometheus'
    static_configs:
      - targets: ['identity-service:8080']