spring:
  application:
    name: prompt-service

  # Database configuration
  datasource:
    url: jdbc:mariadb://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:promptservice}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: org.mariadb.jdbc.Driver

  # JPA configuration
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
    clean-disabled: true

  # Redis configuration
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}

  # Elasticsearch configuration
  elasticsearch:
    uris: ${ES_HOST:localhost}:${ES_PORT:9200}
    index:
      prompt-templates: prompt_templates
      prompt-versions: prompt_versions
      prompt-executions: prompt_executions
      number-of-shards: 5
      number-of-replicas: 1
    connection-timeout: 5000
    socket-timeout: 30000
    max-conn-total: 40
    max-conn-per-route: 10

  data:
    elasticsearch:
      repositories:
        enabled: true

  # Server configuration
  server:
    port: 8082
    servlet:
      context-path: /api/prompt-service

  # Logging configuration
  logging:
    level:
      viettel.dac.promptservice: DEBUG
      org.springframework.data: INFO
      org.springframework.web: INFO
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true

