server:
  port: 8761

spring:
  application:
    name: service-registry
  security:
    user:
      name: ${EUREKA_USERNAME:admin}
      password: ${EUREKA_PASSWORD:admin}
  profiles:
    active: default

# Default profile configuration
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/
  server:
    enable-self-preservation: false
    renewal-percent-threshold: 0.85
    response-cache-update-interval-ms: 5000
    wait-time-in-ms-when-sync-empty: 0

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,info,metrics,prometheus,loggers,env,httptrace
  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
      group:
        liveness:
          include: livenessState,diskSpace
        readiness:
          include: readinessState,diskSpace  # Changed to standard health indicator
    info:
      access: read_only
    metrics:
      access: read_only
    prometheus:
      access: read_only
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.5, 0.75, 0.95, 0.99
    tags:
      application: ${spring.application.name}
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
    git:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true

info:
  application:
    name: ${spring.application.name}
    description: Eureka Service Registry for AgentFlow Platform
    version: @project.version@
  java:
    version: ${java.version}
  spring:
    framework:
      version: ${spring-framework.version}
    boot:
      version: ${spring-boot.version}
  eureka:
    dashboard: ${server.servlet.context-path:}/
  server:
    port: ${server.port}

logging:
  level:
    com.netflix.eureka: INFO
    com.netflix.discovery: INFO
    viettel.dac.serviceregistry: INFO

---
# Docker profile configuration
spring:
  config:
    activate:
      on-profile: docker

eureka:
  instance:
    hostname: service-registry
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka/

---
# Production profile configuration
spring:
  config:
    activate:
      on-profile: prod

eureka:
  instance:
    hostname: ${EUREKA_HOSTNAME:service-registry}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://service-registry:8761/eureka/}
  server:
    enable-self-preservation: true
    renewal-percent-threshold: 0.85